apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: e-commerce
  template:
    metadata:
      labels:
        app: e-commerce
    spec:
      containers:
        - name: server-rep
          image:  fatmafcis/e-website-server
          ports:
            - containerPort: 5000
 